# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65ec1a725105117476ed0db9ceaed9c01b2eb795a7f08b60a99858c447630905e46a9c2207b493c9dc15b67df01d52d0335416a29f5313e8d531fa976bfc9c0b

test:
  secret_key_base: b0598e1c300eb702c829182df3c3ae4e5e46589834e6c68a786c0a22dcc23ee284030e6dbd9d13f31269d7456d058a72daf0ccc3dfd9cf55bb5a4b91d815d7f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
